### ISSUE TITLE
Provide compete Atlas api response in exceptions

### ISSUE THREAD

**Issue by p-mongo** [mongodb-labs/drivers-atlas-testing#36]
I am currently getting the following error from astrolabe:

<pre>
atlasclient.exceptions.AtlasApiError: 404: Not Found. Error Code: 'NOT_ATLAS_GROUP' (GET https://cloud.mongodb.com/api/atlas/v1.0/groups/byName/x)
</pre>

If I inspect the response returned by the api, I see this:

<pre>
(Pdb) response.content
b'{"detail":"Group 5e9d09c5e373b17421f92ca2 is not an Atlas group; use the Cloud Manager Public API at /api/public/v1.0 to access it.","error":404,"errorCode":"NOT_ATLAS_GROUP","parameters":["5e9d09c5e373b17421f92ca2"],"reason":"Not Found"}'
</pre>

As a user of Astrolabe I would like Astrolabe to include all information that api returns into its exceptions so that I can effectively troubleshooting errors.

**Comment by prashantmital** [comment]
Instead of always including the full response by default, I have added the ability to see this output at an elevated logging level. I have also added a brief documentation note on how to use logging levels: https://mongodb-labs.github.io/drivers-atlas-testing/installing-running-locally.html#debugging

Just use the 'debug' logging level and you will see the full request and response. For example:
```
$ astrolabe --log-level DEBUG projects get-one --group-name x1
DEBUG:astrolabe.cli:Atlas Client Configuration:
======================  ===================================
Configuration option    Value
======================  ===================================
Atlas API base URL      https://cloud.mongodb.com/api/atlas
HTTP timeout (s)        10.0
======================  ===================================
DEBUG:atlasclient.client:Request (GET https://cloud.mongodb.com/api/atlas/v1.0/groups/byName/x1 {'auth': <requests.auth.HTTPDigestAuth object at 0x106caffd0>, 'params': {}, 'json': {}, 'timeout': 10.0})
DEBUG:atlasclient.client:Response (GET {'detail': 'The current user is not in the group, or the group does not exist.', 'error': 401, 'errorCode': 'NOT_IN_GROUP', 'parameters': [], 'reason': 'Unauthorized'})
Traceback (most recent call last):
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/bin/astrolabe", line 11, in <module>
    load_entry_point('astrolabe', 'console_scripts', 'astrolabe')()
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/Users/pmital/.pyenv/versions/3.7.5/envs/atlastesting/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Users/pmital/Developer/drivers-atlas-testing/astrolabe/cli.py", line 204, in get_one_project_by_name
    pprint(ctx.obj.groups.byName[group_name].get().data)
  File "/Users/pmital/Developer/drivers-atlas-testing/atlasclient/client.py", line 56, in get
    return self._client.request('GET', self._path, **params)
  File "/Users/pmital/Developer/drivers-atlas-testing/atlasclient/client.py", line 221, in request
    return self.handle_response(method, response)
  File "/Users/pmital/Developer/drivers-atlas-testing/atlasclient/client.py", line 258, in handle_response
    raise AtlasAuthenticationError('401: Unauthorized.', **kwargs)
atlasclient.exceptions.AtlasAuthenticationError: 401: Unauthorized. Error Code: 'NOT_IN_GROUP' (GET https://cloud.mongodb.com/api/atlas/v1.0/groups/byName/x1)
```

**Comment by p-mongo** [comment]
The complete output is not provided. Example: https://gist.github.com/p-mongo/6711c5f08e2926b3cd4ab825876e828b

I have a patch as follows that I am using:

<pre>
carbon% git diff
diff --git a/atlasclient/client.py b/atlasclient/client.py
index d0d8a09..01a9d6a 100644
--- a/atlasclient/client.py
+++ b/atlasclient/client.py
@@ -257,5 +257,6 @@ class AtlasClient:
         if response.status_code == 409:
             raise AtlasApiError('409: Conflict.', **kwargs)
 
+        print(response.content)
         raise AtlasApiError('{}: Unknown.'.format(response.status_code),
                             **kwargs)
</pre>

This patch produces the following line in the linked gist:

<pre>
b'{"detail":"Unexpected error.","error":500,"errorCode":"UNEXPECTED_ERROR","parameters":[],"reason":"Internal Server Error"}'
</pre>

The remainder of the gist (which is output produced by unpatched astrolabe) does not include the `"reason":"Internal Server Error"` part.

**Comment by p-mongo** [comment]
Works correctly after I updated my tree.
