### ISSUE TITLE
Astrolabe does not stop when cluster creation fails

### ISSUE THREAD

**Issue by p-mongo** [mongodb-labs/drivers-atlas-testing#92]
I am seeing this output when running a test:

```
INFO:astrolabe.runner:Initializing cluster '51a1f7e8d0'
DEBUG:atlasclient.client:Request (POST https://cloud.mongodb.com/api/atlas/v1.0/groups/5f5b0c2ccb08f43b11905b20/clusters {'auth': <requests.auth.HTTPDigestAuth object at 0x7f6f084e40d0>, 'params': {}, 'json': {'clusterType': 'REPLICASET', 'providerSettings': {'providerName': 'AWS', 'regionName': 'US_WEST_1', 'instanceSizeName': 'M10'}, 'replicationSpecs': [{'numShards': 1, 'regionsConfig': {'US_WEST_1': {'electableNodes': 1, 'priority': 1}, 'US_EAST_1': {'electableNodes': 1, 'priority': 1}, 'US_EAST_2': {'electableNodes': 1, 'priority': 2}}}], 'name': '51a1f7e8d0'}, 'timeout': 10.0})
DEBUG:atlasclient.client:Response (POST {'detail': 'The required attribute readOnlyNodes was not specified.', 'error': 400, 'errorCode': 'MISSING_ATTRIBUTE', 'parameters': ['readOnlyNodes'], 'reason': 'Bad Request'})
INFO:astrolabe.runner:Waiting for a test cluster to become ready
DEBUG:astrolabe.poller:Polling [<AtlasTestCase: retryReads_primaryTakeover>] [elapsed: 0.00 seconds]
DEBUG:atlasclient.client:Request (GET https://cloud.mongodb.com/api/atlas/v1.0/groups/5f5b0c2ccb08f43b11905b20/clusters/51a1f7e8d0 {'auth': <requests.auth.HTTPDigestAuth object at 0x7f6f084e40d0>, 'params': {}, 'json': {}, 'timeout': 10.0})
DEBUG:atlasclient.client:Response (GET {'detail': 'No cluster named 51a1f7e8d0 exists in group 5f5b0c2ccb08f43b11905b20.', 'error': 404, 'errorCode': 'CLUSTER_NOT_FOUND', 'parameters': ['51a1f7e8d0', '5f5b0c2ccb08f43b11905b20'], 'reason': 'Not Found'})
```

Even though cluster creation failed, astrolabe appears to continue and tries to read it and operate on it.

I expected cluster creation failure to abort execution.

**Comment by prashantmital** [comment]
This is a bug introduced due to the need to handle `DUPLICATE_CLUSTER_NAME` errors. Here https://github.com/mongodb-labs/drivers-atlas-testing/blob/db93e8dfc00c51949b7ce72363167f0e3a8581f9/astrolabe/runner.py#L123 we catch any API exceptions and check for this error code, but we don't raise the exception if the error code does not match. Adding:
```
else:
    raise
```
should fix this issue.

**Comment by prashantmital** [comment]
This is also masking test failures currently occurring in evergreen during cluster initialization:

```
=================================================================================================================================================================================
[2020/09/29 00:43:16.512] Configuration option     Value
[2020/09/29 00:43:16.512] =======================  =================================================================================================================================================================================
[2020/09/29 00:43:16.512] Atlas organization name  Drivers Team
[2020/09/29 00:43:16.512] Atlas project name       drivers-atlas-testing
[2020/09/29 00:43:16.512] Salt for cluster names   drivers_atlas_testing_tests_dotnet_windows__driver~dotnet_master_platform~windows_64_runtime~dotnet_sync_netcoreapp1.1_db93e8dfc00c51949b7ce72363167f0e3a8581f9_20_09_29_00_32_55
[2020/09/29 00:43:16.513] Polling frequency (Hz)   1.0
[2020/09/29 00:43:16.513] Polling timeout (s)      1200.0
[2020/09/29 00:43:16.513] =======================  =================================================================================================================================================================================
[2020/09/29 00:43:16.513] INFO:astrolabe.runner:Loading spec test from file 'C:\\data\\mci\\7c9665b5101f1ac16c6a93769b2a84b8\\astrolabe-src\\tests\\retryReads-toggleServerSideJS.yaml'
[2020/09/29 00:43:16.689] INFO:astrolabe.runner:Verifying organization 'Drivers Team'
[2020/09/29 00:43:16.689] INFO:astrolabe.runner:Successfully verified organization 'Drivers Team'
[2020/09/29 00:43:16.778] INFO:astrolabe.runner:Verifying project 'drivers-atlas-testing'
[2020/09/29 00:43:16.778] INFO:astrolabe.runner:Successfully verified project 'drivers-atlas-testing'
[2020/09/29 00:43:16.910] INFO:astrolabe.runner:Verifying user 'atlasuser'
[2020/09/29 00:43:16.910] INFO:astrolabe.runner:Successfully verified user 'atlasuser'
[2020/09/29 00:43:16.911] INFO:astrolabe.runner:Enabling access from anywhere on project 'drivers-atlas-testing'
[2020/09/29 00:43:16.955] INFO:astrolabe.runner:Successfully enabled access from anywhere on project 'drivers-atlas-testing'
[2020/09/29 00:43:16.955] INFO:astrolabe.runner:Astrolabe Test Plan
[2020/09/29 00:43:16.955] =============================  ====================
[2020/09/29 00:43:16.955] Test name                      Atlas cluster name
[2020/09/29 00:43:16.955] =============================  ====================
[2020/09/29 00:43:16.955] retryReads_toggleServerSideJS  b2b3027f03
[2020/09/29 00:43:16.955] =============================  ====================
[2020/09/29 00:43:17.069] Traceback (most recent call last):
[2020/09/29 00:43:17.069]   File "C:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\Scripts\astrolabe-script.py", line 33, in <module>
[2020/09/29 00:43:17.069]     sys.exit(load_entry_point('astrolabe', 'console_scripts', 'astrolabe')())
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\core.py", line 829, in __call__
[2020/09/29 00:43:17.069]     return self.main(*args, **kwargs)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\core.py", line 782, in main
[2020/09/29 00:43:17.069]     rv = self.invoke(ctx)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\core.py", line 1259, in invoke
[2020/09/29 00:43:17.069]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\core.py", line 1259, in invoke
[2020/09/29 00:43:17.069]     return _process_result(sub_ctx.command.invoke(sub_ctx))
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\core.py", line 1066, in invoke
[2020/09/29 00:43:17.069]     return ctx.invoke(self.callback, **ctx.params)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\core.py", line 610, in invoke
[2020/09/29 00:43:17.069]     return callback(*args, **kwargs)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabevenv\lib\site-packages\click\decorators.py", line 21, in new_func
[2020/09/29 00:43:17.069]     return f(get_current_context(), *args, **kwargs)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabe\cli.py", line 441, in run_single_test
[2020/09/29 00:43:17.069]     failed = runner.run()
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabe\runner.py", line 310, in run
[2020/09/29 00:43:17.069]     case.initialize()
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\astrolabe\runner.py", line 134, in initialize
[2020/09/29 00:43:17.069]     clusters[self.cluster_name].processArgs.patch(**process_args)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\atlasclient\client.py", line 61, in patch
[2020/09/29 00:43:17.069]     return self._client.request('PATCH', self._path, **params)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\atlasclient\client.py", line 218, in request
[2020/09/29 00:43:17.069]     return self.handle_response(method, response)
[2020/09/29 00:43:17.069]   File "c:\data\mci\7c9665b5101f1ac16c6a93769b2a84b8\astrolabe-src\atlasclient\client.py", line 261, in handle_response
[2020/09/29 00:43:17.069]     raise AtlasApiError('404: Not Found.', **kwargs)
[2020/09/29 00:43:17.069] atlasclient.exceptions.AtlasApiError: 404: Not Found. Error Code: 'CLUSTER_NOT_FOUND' (PATCH https://cloud-dev.mongodb.com/api/atlas/v1.0/groups/5f72646d3667024f68c9845f/clusters/b2b3027f03/processArgs)
```

https://evergreen.mongodb.com/version/drivers_atlas_testing_db93e8dfc00c51949b7ce72363167f0e3a8581f9
